version: '2'

services:
  guacamole-client:
   extends:
    file: ./modules/docker-compose.yml
    service: guacamole-client
   image: nanocloud/guacamole-client:indiana

  guacamole-server:
   extends:
    file: ./modules/docker-compose.yml
    service: guacamole-server

  nanocloud-backend:
   extends:
    file: ./modules/docker-compose.yml
    service: nanocloud-backend
   image: nanocloud/nanocloud-backend:indiana
   volumes_from:
    - nanocloud-frontend

  nanocloud-frontend:
   extends:
    file: ./modules/docker-compose.yml
    service: nanocloud-backend
   image: nanocloud/nanocloud-frontend:indiana
   container_name: "nanocloud-frontend"
   volumes:
    - /opt/front

  proxy:
   extends:
    file: ./modules/docker-compose.yml
    service: proxy

  rabbitmq:
   extends:
    file: ./modules/docker-compose.yml
    service: rabbitmq

  postgres:
   extends:
    file: ./modules/docker-compose.yml
    service: postgres

  apps-module:
   extends:
    file: ./modules/docker-compose.yml
    service: apps-module
   image: nanocloud/apps-module:indiana

  history-module:
   extends:
    file: ./modules/docker-compose.yml
    service: history-module
   image: nanocloud/history-module:indiana

  iaas-module:
   extends:
    file: ./modules/docker-compose.yml
    service: iaas-module
   image: nanocloud/iaas-module:indiana

  ldap-module:
   extends:
    file: ./modules/docker-compose.yml
    service: ldap-module
   image: nanocloud/ldap-module:indiana

  users-module:
   extends:
    file: ./modules/docker-compose.yml
    service: users-module
   image: nanocloud/users-module:indiana
